export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";

export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_FAILURE = "FETCH_COUNTRIES_FAILURE";

export const FETCH_CITIES = "FETCH_CITIES";
export const FETCH_CITIES_SUCCESS = "FETCH_CITIES_SUCCESS";
export const FETCH_CITIES_FAILURE = "FETCH_CITIES_FAILURE";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const FETCH_PROFILE = "FETCH_PROFILE";
export const SET_PROFILE = "SET_PROFILE";
export const UNSET_PROFILE = "UNSET_PROFILE";

//Todo esto tengo que hacer jaja

export const FECTCH_EVENT_DETAIL = "FETCH_EVENT_DETAIL";
export const FECTCH_EVENT_DETAIL_SUCCESS = "FETCH_EVENT_DETAIL_SUCCESS";
export const FECTCH_EVENT_DETAIL_FAILURE = "FETCH_EVENT_DETAIL_FAILURE";

export const FETCH_EVENT_BID = "FETCH_EVENT_BID";
export const FETCH_EVENT_BID_SUCCESS = "FETCH_EVENT_BID_SUCCESS";
export const FETCH_EVENT_BID_FAILURE = "FETCH_EVENT_BID_FAILURE";

export const FETCH_EVENT_PLACE = "FETCH_EVENT_PLACE";
export const FETCH_EVENT_PLACE_SUCCESS = "FETCH_EVENT_PLACE_SUCCESS";
export const FETCH_EVENT_PLACE_FAILURE = "FETCH_EVENT_PLACE_FAILURE";

export const FETCH_USER_BIDS = "FETCH_USER_BIDS";
export const FETCH_USER_BIDS_SUCCESS = "FETCH_USER_BIDS_SUCCESS";
export const FETCH_USER_BIDS_FAILURE = "FETCH_USER_BIDS_FAILURE";